version: '3'

services:

  jupyter:
    image: ist769/jupyter_pyspark:20210924b 
    hostname: jupyter
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=SU2orange!       
    ports:
      - "8888:8888"
    volumes: 
      - ./work:/home/jovyan/work
 
  couchbase:
    image: couchbase:latest
    hostname: couchbase
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
    volumes:
      - ./data:/opt/couchbase/data
    environment:
      - COUCHBASE_USERNAME=admin
      - COUCHBASE_PASSWORD=password